/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthTransactionsRouteImport } from './routes/_auth/transactions'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthReportsRouteImport } from './routes/_auth/reports'
import { Route as AuthBudgetsRouteImport } from './routes/_auth/budgets'
import { Route as AuthAiRouteImport } from './routes/_auth/ai'
import { Route as AuthAccountsRouteImport } from './routes/_auth/accounts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransactionsRoute = AuthTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBudgetsRoute = AuthBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAiRoute = AuthAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountsRoute = AuthAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthAccountsRoute
  '/ai': typeof AuthAiRoute
  '/budgets': typeof AuthBudgetsRoute
  '/reports': typeof AuthReportsRoute
  '/settings': typeof AuthSettingsRoute
  '/transactions': typeof AuthTransactionsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounts': typeof AuthAccountsRoute
  '/ai': typeof AuthAiRoute
  '/budgets': typeof AuthBudgetsRoute
  '/reports': typeof AuthReportsRoute
  '/settings': typeof AuthSettingsRoute
  '/transactions': typeof AuthTransactionsRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/accounts': typeof AuthAccountsRoute
  '/_auth/ai': typeof AuthAiRoute
  '/_auth/budgets': typeof AuthBudgetsRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/transactions': typeof AuthTransactionsRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/ai'
    | '/budgets'
    | '/reports'
    | '/settings'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounts'
    | '/ai'
    | '/budgets'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/accounts'
    | '/_auth/ai'
    | '/_auth/budgets'
    | '/_auth/reports'
    | '/_auth/settings'
    | '/_auth/transactions'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transactions': {
      id: '/_auth/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthTransactionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/budgets': {
      id: '/_auth/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthBudgetsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ai': {
      id: '/_auth/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthAiRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounts': {
      id: '/_auth/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthAccountsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountsRoute: typeof AuthAccountsRoute
  AuthAiRoute: typeof AuthAiRoute
  AuthBudgetsRoute: typeof AuthBudgetsRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthTransactionsRoute: typeof AuthTransactionsRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountsRoute: AuthAccountsRoute,
  AuthAiRoute: AuthAiRoute,
  AuthBudgetsRoute: AuthBudgetsRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthTransactionsRoute: AuthTransactionsRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
